server:
  servlet:
    context-path: /api/v1
  port: 8090

spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:h2:mem:custumerdb
    driverClassName: org.h2.Driver
    username: admin
    password: admin
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    format_sql: true

  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
