spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      ribbon:
        enable: false
    gateway:
      locator:
        enable: true
      routes:
        - id: customer-middleend-route
          uri: lb://CUSTOMER-MIDDLEEND
          predicates:
            - Path= /api/v1/customers/**
