server:
  servlet:
    context-path: /api/v1
  port: 8084

spring:
  ## application name
  application:
    name: customer-service
  ## database config H2
  datasource:
    driverClassName: org.postgresql.Driver
<<<<<<< HEAD
    url: jdbc:postgresql://localhost:5433/customer_db?currentSchema=customer
    username: postgres
    password: 12345
=======
    url: ${SERVER_DATABASE_POSTGRES:jdbc:postgresql://localhost:5432/customer_db?currentSchema=customer}
    username: Admin
    password: Admin
>>>>>>> branch 'desarrollo' of https://github.com/fquisiguina/Proyecto-grupo-6.git

  ## jpa structure config
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    format_sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8056/eureka