spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      ribbon:
        enable: false
    gateway:
      locator:
        enable: true
      routes:
        - id: account-middleend-route
          uri: lb://ACCOUNT-MIDDLEEND
          predicates:
            - Path= /api/v1/accounts/**
        - id: customer-middleend-route
          uri: lb://customer-middleend
          predicates:
            - Path= /api/v1/customers/**
        - id: movement-middleend-route
          uri: lb://MOVEMENT-MIDDLEEND
          predicates:
            - Path= /api/v1/movements/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8056/eureka/
