spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      ribbon:
        enable: false
    gateway:
      locator:
        enable: true
      routes:
        - id: account-middleend-route
          uri: lb://ACCOUNT-MIDDLEEND
          predicates:
            - Path= /api/v1/accounts/**
        - id: customer-middleend-route
          uri: lb://CUSTOMER-MIDDLEEND
          predicates:
            - Path= /api/v1/customers/**

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
